In [80]:
import pandas as pd
import numpy as np
 
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris


Zadanie 1

In [81]:
data = load_iris()
X = data.data
y = data.target

sr = np.mean(X)
odchstf = np.std(X)

X_std = (X - sr)/odchstf

print(X)
print(X_std)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Macierz kowariancji

In [82]:
kowM = np.cov(X_std)

Obliczenie wartości i wektorów własnych macierzy kowariancji

In [83]:
wartości,wektory = np.linalg.eig(kowM)
print(wektory,wartości)

[[ 7.71455536e-02+0.j         -1.20972089e-01+0.j
  -3.26622809e-03+0.j         ...  9.47812999e-02+0.01357492j
   9.47812999e-02-0.01357492j -1.88270331e-16+0.j        ]
 [ 7.53653474e-02+0.j         -9.95152089e-02+0.j
  -8.23623956e-02+0.j         ...  1.49238789e-02+0.00412015j
   1.49238789e-02-0.00412015j -9.23147750e-17+0.j        ]
 [ 7.09468726e-02+0.j         -1.09970613e-01+0.j
  -1.10144843e-02+0.j         ... -1.62670416e-03+0.00589679j
  -1.62670416e-03-0.00589679j -1.75109728e-16+0.j        ]
 ...
 [ 8.31410074e-02+0.j          5.74042233e-02+0.j
  -3.47473998e-02+0.j         ...  5.22576142e-03-0.04132804j
   5.22576142e-03+0.04132804j -3.64022232e-16+0.j        ]
 [ 7.21000291e-02+0.j          5.42322798e-02+0.j
   1.00615536e-01+0.j         ...  1.16240853e-02-0.01104058j
   1.16240853e-02+0.01104058j  7.93828421e-16+0.j        ]
 [ 7.57544492e-02+0.j          5.70107447e-02+0.j
   1.25720612e-01+0.j         ... -4.78068249e-02-0.00213171j
  -4.78068249e-02+0.00213171

Przekształcenie danych

In [84]:
k = 10
print(min(wartości))

print(X_std.shape)
print(wektory.shape)
Z = X_std.T @ wektory

Z1 = X_std.T @ wektory[:,:k]



(-4.662374361459756e-15-5.639054615493966e-16j)
(150, 4)
(150, 150)
